### ISSUE TITLE
ESM Login Password not base64 encoded

### ISSUE THREAD

**Issue by Balzu** [mfesiem/msiempy#100]
**Describe**
The password is not base64 encoded in *msiempy\core\session.py*

**Details:**
Password is not base64 encoded in *msiempy\core\session.py*. Because of this, I was not able to login
to ESM. I don't know if it is supposed to be base64 encoded always, or if there are version that accept it not base-64 encoded.

        def login(self, retry=1):
        """
        Authentication is done lazily upon the first call to `msiempy.core.session.NitroSession.request` method, but you can still do 
        it manually by calling this method.
        
        Raises:
            `msiempy.core.session.NitroError` if login fails
        """
        userb64 = tob64(self.config.user)
        passb64 = self.config.passwd

**Comment by Balzu** [comment]
I was reviewing the information, actually it is envisioned to write the password base64 encoded in the config file, so no issue is present

**Comment by tristanlatr** [comment]
Great to hear!
Happy coding!
