### ISSUE TITLE
notifyGetTriggeredNotification being removed from external API

### ISSUE THREAD

**Issue by iJebus** [mfesiem/msiempy#11]
More of a heads up than a current bug but looking at the 10.4 release notes, the `notifyGetTriggeredNotification` external API endpoint is being "removed to improve security", among some 77 others. 

Looking for another way to get alarm details out of the API surfaces; I had hoped to use `qryExecuteDetail` with the `TRIGGERED_ALARMS_QUERY` type supplied but the API spits `Unsupported query type: TRIGGERED_ALARMS_QUERY` back at me, so go figure.

https://github.com/mfesiem/msiempy/blob/85d6ed8dd755eabcf913248dd51f5583757407e6/msiempy/params.py#L201

**Comment by tristanlatr** [comment]
Hello,

Thanks for the reporting ! Very sad news... 
I'll try to look into finding another way.

This update affects also version 11.2. Here are links to release notes
- 11.2 : https://kc.mcafee.com/resources/sites/MCAFEE/content/live/PRODUCT_DOCUMENTATION/28000/PD28336/en_US/ESM_1120_rn_0-00_en-us.PDF
- 10.4 : https://kc.mcafee.com/resources/sites/MCAFEE/content/live/PRODUCT_DOCUMENTATION/28000/PD28356/en_US/ESM_1040_rn_0-00_en-us.PDF

**Comment by andywalden** [comment]
I signed off on the API changes and thought that one would stay. I'm confirming the plan with the API dev and will update.

**Comment by iJebus** [comment]
A hot-fix for 10.4 that re-enables some of the endpoints was released to me yesterday. How widely available or when that will be released generally is a bit of a question mark though.

**Comment by andywalden** [comment]
Yep, that didn't happen accidentally. 11.2.0 was pulled from the upgrade site and 11.2.1 should include the method. 10.4 also.

**Comment by tristanlatr** [comment]
Hi, it seems that the method were remove from the version 11.2.1 as well.
Do we know any work around ?

**Comment by tristanlatr** [comment]
Update : This is currently being fixed at https://github.com/mfesiem/msiempy/pull/23
