### ISSUE TITLE
Documentation generation problems

### ISSUE THREAD

**Issue by satelliteoflove** [mfesiem/msiempy#13]
I'm unable to generate the documentation using Sphinx, and the docs on readthedocs appears to be missing.

Expected result: issuing "make <target>" from ./msiempy/docs/ should generate docs.

Actual result: multiple errors in autodoc:
`WARNING: autodoc: failed to import module 'alarm' from module 'msiempy'; the following exception was raised: No module named 'msiempy'`

Attempts to resolve the issue include modifying the second parameter in conf.py file's "sys.path.insert" function call to "..", "../msiempy/".

**Comment by satelliteoflove** [comment]
Note: updating the line in conf.py to
`sys.path.insert(0, os.path.abspath('../..'))`
does get the process further along but the autodoc system now complains of the lack of the "tqdm" module being missing instead of "msiempy".

In addition, errors related to params.py and session.py are generated related to unexpected indents and block quotes ending without a blank line (unexpected unindent).

**Comment by satelliteoflove** [comment]
After installing other python modules from requirements.txt and making the above edit to docs/source/conf.py, I can make documentation for some targets (though not all).  There are numerous indentation/block quote warnings, as well as two more specific warnings:

`checking consistency... /<basedir>/msiempy/docs/source/modules.rst: WARNING: document isn't included in any toctree`

`copying static files... WARNING: html_static_path entry '/<basedir>/msiempy/docs/source/_static' does not exist`

**Comment by tristanlatr** [comment]
Hello,

We moved from Shpinx to pdoc3 because it's more easy to use.
Thanks for the reporting though :)
