### ISSUE TITLE
Define Requirements for Test ESM

### ISSUE THREAD

**Issue by andywalden** [mfesiem/msiempy#39]
In the interest of creating a more stable live test environment, what are the requirements for a test ESM? It should have alarms, watchlists, events, etc - going how far back? Ideally testing would be limited to shorter timeframes but this requires some amount of intent to ensure those conditions always exist on the ESM for the test. Can we define what needs to exist for tests not to fail?

**Comment by tristanlatr** [comment]
Hi,

Thanks for raising this important question.
The test environment should indeed be fed with events and alarms on a regular basis. 
Presently, testing queries uses `CURRENT_YEAR` time range, it'll be a na issue the first of January...
In order to test Alarm and Event filtering, not all events should be logged with the same source IP, and several types of Alarms should be triggered. 
I couldn't tell a specific list of technical requirements, I don't know  your capacity to auto create alarms and events....

**Comment by andywalden** [comment]
3 ESMs  to track the branches. I have a plan.

**Comment by tristanlatr** [comment]
Hey @andywalden 

It looks like the test ESM is empty of Alarms, Events and DataSources ?
See tests logs for details (https://github.com/mfesiem/msiempy/actions)

**Comment by andywalden** [comment]
It's back up now. Here are the data points:

1. Sorry about the delay. I spent some time trying to investigate why it happened before reinstalling it.

2. What happened is that the Local Receiver for the combo ESM/ERC was deleted. This isn't possible to do in the UI. 

3. I've seen this once before when running tests add/removing datasources. I chalked it up to a fluke since I was automating it and assumed I had accidentally slipped the ERC ID into the loop and deleted it somehow. I also had the thought that I should file a bug since this really shouldn't be possible. 

4. I wasn't able to figure out what happened with the output at travis-ci. I'm going to continue looking into it some more.

5. I'll actually file a internal bug too.

6. Not all the tests work still and I'm currently working on that.

**Comment by tristanlatr** [comment]
Thanks for the follow up. All the tests (authenticated and unauthenticated) are automatically ran with github actions on windows, ubuntu and macos. We can rerun them by clicking on the rerun checks button. Here is the current PR checks : https://github.com/mfesiem/msiempy/commit/d768cdac5033ba8205c31d117d4f36ebfae3ecea/checks?check_suite_id=358729476

**Comment by tristanlatr** [comment]
Hey @andywalden , it looks like the test ESM is unavailable. "The application is unavailable at this time. Wait a moment or refresh page to check for availability."...

**Comment by tristanlatr** [comment]
Other thing, I've changed the _insert_rec_info method of the DevTree, please review this bugfix just to be sure I didn't break something else. Thanks a lot.
https://github.com/mfesiem/msiempy/commit/81327ac6196b0979bc9ff4cc888e9c2fe76b8cc5

**Comment by andywalden** [comment]
I kicked the ESM as soon as I saw this - I assume it's all fine. 

Been busy transitioning to a new company. I'll look at the code now. Thanks.

**Comment by andywalden** [comment]
https://github.com/mfesiem/msiempy/commit/81327ac6196b0979bc9ff4cc888e9c2fe76b8cc5 looks fine enough to me. Thanks.
