### ISSUE TITLE
Test ESM is broken

### ISSUE THREAD

**Issue by tristanlatr** [mfesiem/msiempy#59]
**Describe**
Test ESM is broken

<img width="852" alt="by default 2019-12-04 at 2 15 11 PM" src="https://user-images.githubusercontent.com/19967168/70173265-7e6ef200-16a0-11ea-9a33-8b66b927453c.png">

**Comment by andywalden** [comment]
That's just a chrome error though, right? It doesn't like the cert.

**Comment by tristanlatr** [comment]
Yes, probably
