### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by KusalJ** [mfesiem/msiempy#65]
Typo causes **"Interpolation failed probably because of the private API calls formatting... Unexpected behaviours can happend."** Error.

**Solution**
`        "ds_last_times": ("QRY%5FGETDEVICELASTALERTTIME","""{}"""),
`
Should be:
`        "ds_last_times": ("QRY_GETDEVICELASTALERTTIME","""{}"""),
`

**Comment by tristanlatr** [comment]
Hello, 

Thank you for raising this concern.

This warning can be ignored if no parameters are interpolated in the data part. Which is empty here. So the warning , ideally should not display.

I'm not sure the private API calls would work with unencoded method strings...
@andywalden @rhart211 ideas ?

Thanks

**Comment by tristanlatr** [comment]
Edit: just checked and yes indeed it should work with the dashes not encoded, I'll add the proposed changes in th e next release
